<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Scada.Core/Scada.Core.csproj" />
    <ProjectReference Include="../Scada.Drivers/Scada.Drivers.csproj" />
    <ProjectReference Include="../Scada.Drivers.Dnp3.OpenDnp3/Scada.Drivers.Dnp3.OpenDnp3.csproj" />
    <ProjectReference Include="../Scada.Engineering/Scada.Engineering.csproj" />
  </ItemGroup>
</Project>
