<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Scada.Core/Scada.Core.csproj" />
    <ProjectReference Include="../Scada.Drivers/Scada.Drivers.csproj" />
    <ProjectReference Include="../Scada.Historian/Scada.Historian.csproj" />
    <ProjectReference Include="../Scada.Engineering/Scada.Engineering.csproj" />
  </ItemGroup>
</Project>
