import { expect, test } from '@playwright/test';
import type { ScriptAssistantCatalog } from '../src/engineering/scripts/scriptAssistantModel';
import { validateScriptAssistantReferences } from '../src/engineering/scripts/scriptAssistantReferenceValidation';

const catalog = {
  tags: [
    {
      kind: 'tag',
      id: 'tag-live',
      name: 'Live',
      path: 'Plant.Live',
      canonicalReference: 'tag-live',
      dataType: 'Double',
      engineeringUnit: null,
      description: null,
      readOnly: false,
      sourceLabel: null,
      dataSourceId: null,
      driver: null,
      sourceIdentityStatus: 'none',
      snippets: []
    }
  ],
  screens: [
    {
      kind: 'screen',
      id: 'screen-main',
      key: 'main',
      name: 'Main',
      route: '/main',
      objects: [
        {
          kind: 'visual-object',
          id: 'button-live',
          key: 'ButtonLive',
          type: 'core.button',
          visualDefinitionId: 'screen-main',
          canonicalReference: 'screen-main/button-live',
          dynamoKey: null,
          equipmentPath: null,
          events: ['Click'],
          properties: [
            {
              kind: 'visual-property',
              key: 'visible',
              type: 'boolean',
              category: null,
              currentValue: true,
              defaultValue: true,
              runtimeReadable: true,
              runtimeWritable: true,
              supportsBinding: true,
              animatable: false,
              allowedValues: [],
              snippets: []
            }
          ],
          publicDynamoParameters: [],
          children: [],
          schemaStatus: 'canonical'
        }
      ]
    }
  ],
  popups: [],
  clientMemory: [
    {
      kind: 'client-memory',
      id: 'memory-live',
      name: 'Memory',
      path: 'Client.Live',
      dataType: 'String',
      readOnly: false,
      initialValue: '',
      sourceKey: 'builtin.memory.client',
      sourceName: 'Client Memory',
      snippets: []
    }
  ],
  capabilities: []
} as unknown as ScriptAssistantCatalog;

test('literal references generated by the assistant validate against the current project catalog', () => {
  const source = [
    'from elite_scada import tag_read, tag_write, visual_property_read, client_memory_read',
    'value = await tag_read("tag-live")',
    'await tag_write("tag-live", 1)',
    'visible = await visual_property_read("screen-main/button-live", "visible")',
    'mode = await client_memory_read("memory-live")'
  ].join('\n');

  expect(validateScriptAssistantReferences(source, catalog)).toEqual([]);
});

test('deleted TAG, object, property and Client Memory references remain invalid and are reported without substitution', () => {
  const source = [
    'value = await tag_read("tag-deleted")',
    'visible = await visual_property_read("button-deleted", "visible")',
    'text = await visual_property_read("screen-main/button-live", "text")',
    'mode = await client_memory_read("memory-deleted")'
  ].join('\n');

  expect(validateScriptAssistantReferences(source, catalog)).toEqual([
    expect.objectContaining({ code: 'SCRIPT_REFERENCE_TAG_MISSING', line: 1, reference: 'tag-deleted' }),
    expect.objectContaining({ code: 'SCRIPT_REFERENCE_OBJECT_MISSING', line: 2, reference: 'button-deleted', propertyKey: 'visible' }),
    expect.objectContaining({ code: 'SCRIPT_REFERENCE_PROPERTY_MISSING', line: 3, reference: 'button-live', propertyKey: 'text' }),
    expect.objectContaining({ code: 'SCRIPT_REFERENCE_CLIENT_MEMORY_MISSING', line: 4, reference: 'memory-deleted' })
  ]);

  expect(JSON.stringify(validateScriptAssistantReferences(source, catalog))).not.toContain('tag-live');
});

test('dynamic Python references are not guessed or rewritten by the conservative validator', () => {
  const source = [
    'tag_id = choose_tag()',
    'value = await tag_read(tag_id)',
    'object_id = current_object()',
    'await visual_property_write(object_id, "visible", True)'
  ].join('\n');

  expect(validateScriptAssistantReferences(source, catalog)).toEqual([]);
});


test('legacy objectKey literals are warned without silent migration and stable candidate is explicit', () => {
  const source = [
    'value = await visual_property_read("ButtonLive", "visible")',
    'await visual_property_write("ButtonLive", "visible", False)',
    'await visual_tween_request({"targetReference": "ButtonLive", "propertyKey": "x", "targetValue": 10, "durationMs": 100})'
  ].join('\n');

  const diagnostics = validateScriptAssistantReferences(source, catalog);
  expect(diagnostics).toHaveLength(3);
  expect(diagnostics.every(item => item.code === 'SCRIPT_REFERENCE_LEGACY_OBJECT_KEY')).toBeTruthy();
  expect(diagnostics.every(item => item.canonicalReference === 'screen-main/button-live')).toBeTruthy();
  expect(source).toContain('"ButtonLive"');
});

test('ambiguous legacy Key does not invent a migration target', () => {
  const ambiguous = {
    ...catalog,
    popups: [{
      kind: 'popup',
      id: 'popup-other',
      key: 'other',
      name: 'Other',
      route: null,
      objects: [{
        ...catalog.screens[0].objects[0],
        visualDefinitionId: 'popup-other',
        id: 'other-button',
        canonicalReference: 'popup-other/other-button'
      }]
    }]
  } as unknown as ScriptAssistantCatalog;

  const diagnostic = validateScriptAssistantReferences(
    'value = await visual_property_read("ButtonLive", "visible")',
    ambiguous
  )[0];
  expect(diagnostic).toMatchObject({
    code: 'SCRIPT_REFERENCE_LEGACY_OBJECT_KEY_AMBIGUOUS',
    reference: 'ButtonLive'
  });
  expect(diagnostic.canonicalReference).toBeUndefined();
});
