<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>EliteSCADA.LicenseGenerator</AssemblyName>
    <RootNamespace>EliteSCADA.LicenseGenerator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Scada.Core/Scada.Core.csproj" />
  </ItemGroup>
</Project>
