import type { EngineeringLocale } from './i18n';

export function projectManagementCopy(locale: EngineeringLocale) {
  if (locale === 'en') return {
    eyebrow: 'Canonical project portability',
    title: 'Project Management',
    description: 'Export, inspect, preview and restore Engineering through the same public contracts used by the product.',
    loading: 'Loading project portability context…', loadFailed: 'Project portability context could not be loaded.', retry: 'Try again',
    refresh: 'Refresh', refreshing: 'Refreshing…', project: 'Project', unnamed: 'Unnamed project', noKey: 'No project key',
    working: 'Working', dirty: 'Unsaved changes', clean: 'Clean', baseRevision: 'Base revision', none: 'None',
    canonicalSchema: 'Canonical schema', changeVersion: 'Change version',
    jsonTitle: 'Canonical Engineering JSON', jsonDescription: 'Portable technical representation for review, versioning and controlled import.',
    downloadJson: 'Download JSON', jsonSource: 'JSON import source', chooseJson: 'Choose JSON file', noFile: 'No file selected',
    sourceSchema: 'Source schema', schemaVersion: 'Schema version', invalidJson: 'The selected file is not valid JSON.',
    mergeMode: 'Merge mode', previewJson: 'Preview JSON import', applyJson: 'Apply JSON import',
    packageTitle: 'Application file (.escadapkg)', packageDescription: 'Single portable application file with manifest, canonical Engineering, project images and integrity checks. Working and Revisions remain persisted by the server.',
    downloadPackage: 'Save application as…', packageSource: 'Application file to open', choosePackage: 'Choose .escadapkg file', inspectPackage: 'Inspect application',
    previewPackage: 'Preview restore', restorePackage: 'Restore into Working', packageNotInspected: 'Select and inspect a package before previewing restore.',
    manifest: 'Package manifest', packageId: 'Package ID', createdAt: 'Created', format: 'Format', projectIdentity: 'Package project',
    packageSchema: 'Engineering schema', packagePayload: 'Engineering contents', items: 'entities', checksum: 'SHA-256', bytes: 'bytes',
    previewTitle: 'Preview result', create: 'Create', update: 'Update', skip: 'Skip', errors: 'Errors', canApply: 'Can apply', blocked: 'Blocked',
    noPreview: 'No Preview has been validated for this source and merge mode.', issues: 'Validation issues', noIssues: 'No validation issues reported.',
    secretsTitle: 'Backup boundary', secretsHint: 'Project files never embed secret material. Secret references may be preserved, but credentials remain in the configured secret provider.',
    excludedTitle: 'Not included in .escadapkg v1', excluded: ['Historian time-series samples', 'Transient Runtime values', 'Active sessions', 'Passwords, tokens, private keys or credential hashes', 'Deployment and operating-system secrets'],
    applyConfirmTitle: 'Apply canonical JSON to Working?', applyConfirmDescription: 'Only the exact source and merge mode validated by Preview will be applied. If Working changed meanwhile, the server rejects the operation with a conflict.', applyConfirm: 'Apply validated JSON',
    restoreConfirmTitle: 'Restore project backup into Working?', restoreConfirmDescription: 'This mutates the current Engineering Working workspace using the validated package and merge mode. Published and Active remain separate lifecycle operations.', restoreConfirm: 'Restore validated backup',
    cancel: 'Cancel', savedJson: 'Canonical Engineering JSON downloaded.', savedPackage: 'Application file saved.',
    jsonApplied: 'Canonical JSON applied to Working.', packageRestored: 'Project backup restored into Working.', packageInspected: 'Package integrity and manifest validated.',
    previewReady: 'Preview validated. Apply remains bound to this exact source, mode and Workspace version.',
    authorityTitle: 'Server authority preserved', authorityHint: 'Validation, merge semantics, EngineeringModify authorization, Audit and optimistic-concurrency conflict protection remain server-side. This workspace does not create a private project model or trusted operator identity.'
  };

  if (locale === 'es') return {
    eyebrow: 'Portabilidad canónica del proyecto', title: 'Gestión del proyecto',
    description: 'Exporte, inspeccione, previsualice y restaure Engineering mediante los mismos contratos públicos usados por el producto.',
    loading: 'Cargando contexto de portabilidad…', loadFailed: 'No fue posible cargar el contexto de portabilidad.', retry: 'Intentar nuevamente',
    refresh: 'Actualizar', refreshing: 'Actualizando…', project: 'Proyecto', unnamed: 'Proyecto sin nombre', noKey: 'Sin clave de proyecto',
    working: 'Working', dirty: 'Cambios sin guardar', clean: 'Sin cambios', baseRevision: 'Revisión base', none: 'Ninguna',
    canonicalSchema: 'Schema canónico', changeVersion: 'Versión de cambio',
    jsonTitle: 'JSON canónico de Engineering', jsonDescription: 'Representación técnica portable para revisión, versionado e importación controlada.',
    downloadJson: 'Descargar JSON', jsonSource: 'Origen JSON', chooseJson: 'Elegir archivo JSON', noFile: 'Ningún archivo seleccionado',
    sourceSchema: 'Schema de origen', schemaVersion: 'Versión del schema', invalidJson: 'El archivo seleccionado no es JSON válido.',
    mergeMode: 'Modo de merge', previewJson: 'Preview de importación', applyJson: 'Aplicar importación JSON',
    packageTitle: 'Archivo de aplicación (.escadapkg)', packageDescription: 'Archivo único y portable con manifiesto, Engineering canónico, imágenes del proyecto y controles de integridad. Working y Revisions permanecen persistidos por el servidor.',
    downloadPackage: 'Guardar aplicación como…', packageSource: 'Archivo de aplicación para abrir', choosePackage: 'Elegir archivo .escadapkg', inspectPackage: 'Inspeccionar aplicación',
    previewPackage: 'Preview de restore', restorePackage: 'Restaurar en Working', packageNotInspected: 'Seleccione e inspeccione un paquete antes del Preview.',
    manifest: 'Manifiesto del paquete', packageId: 'ID del paquete', createdAt: 'Creado', format: 'Formato', projectIdentity: 'Proyecto del paquete',
    packageSchema: 'Schema de Engineering', packagePayload: 'Contenido de Engineering', items: 'entidades', checksum: 'SHA-256', bytes: 'bytes',
    previewTitle: 'Resultado del Preview', create: 'Crear', update: 'Actualizar', skip: 'Omitir', errors: 'Errores', canApply: 'Puede aplicar', blocked: 'Bloqueado',
    noPreview: 'No existe un Preview validado para este origen y modo de merge.', issues: 'Problemas de validación', noIssues: 'No se reportaron problemas de validación.',
    secretsTitle: 'Límite del backup', secretsHint: 'Los archivos del proyecto nunca incluyen material secreto. Las referencias pueden conservarse, pero las credenciales permanecen en el proveedor de secretos configurado.',
    excludedTitle: 'No incluido en .escadapkg v1', excluded: ['Muestras de series temporales del historiador', 'Valores transitorios de Runtime', 'Sesiones activas', 'Contraseñas, tokens, claves privadas o hashes de credenciales', 'Secretos del despliegue y del sistema operativo'],
    applyConfirmTitle: '¿Aplicar JSON canónico a Working?', applyConfirmDescription: 'Solo se aplicará el origen y modo exactos validados por Preview. Si Working cambió mientras tanto, el servidor rechaza la operación por conflicto.', applyConfirm: 'Aplicar JSON validado',
    restoreConfirmTitle: '¿Restaurar el backup en Working?', restoreConfirmDescription: 'Esto modifica el Engineering Working actual usando el paquete y modo validados. Published y Active siguen siendo operaciones separadas del ciclo.', restoreConfirm: 'Restaurar backup validado',
    cancel: 'Cancelar', savedJson: 'JSON canónico de Engineering descargado.', savedPackage: 'Archivo de aplicación guardado.',
    jsonApplied: 'JSON canónico aplicado a Working.', packageRestored: 'Backup restaurado en Working.', packageInspected: 'Integridad y manifiesto del paquete validados.',
    previewReady: 'Preview validado. Apply permanece vinculado al origen, modo y versión exactos del Workspace.',
    authorityTitle: 'Autoridad del servidor preservada', authorityHint: 'Validación, merge, autorización EngineeringModify, Audit y protección de concurrencia permanecen en el servidor. Este workspace no crea un modelo privado ni identidad confiable del operador.'
  };

  return {
    eyebrow: 'Portabilidade canônica do projeto', title: 'Gerenciamento do projeto',
    description: 'Exporte, inspecione, valide e restaure o Engineering pelos mesmos contratos públicos usados pelo produto.',
    loading: 'Carregando contexto de portabilidade…', loadFailed: 'Não foi possível carregar o contexto de portabilidade.', retry: 'Tentar novamente',
    refresh: 'Atualizar', refreshing: 'Atualizando…', project: 'Projeto', unnamed: 'Projeto sem nome', noKey: 'Sem chave do projeto',
    working: 'Working', dirty: 'Alterações não salvas', clean: 'Sem alterações', baseRevision: 'Revisão base', none: 'Nenhuma',
    canonicalSchema: 'Schema canônico', changeVersion: 'Versão de mudança',
    jsonTitle: 'JSON canônico do Engineering', jsonDescription: 'Representação técnica portável para revisão, versionamento e importação controlada.',
    downloadJson: 'Baixar JSON', jsonSource: 'Origem da importação JSON', chooseJson: 'Escolher arquivo JSON', noFile: 'Nenhum arquivo selecionado',
    sourceSchema: 'Schema da origem', schemaVersion: 'Versão do schema', invalidJson: 'O arquivo selecionado não é um JSON válido.',
    mergeMode: 'Modo de merge', previewJson: 'Validar Preview do JSON', applyJson: 'Aplicar importação JSON',
    packageTitle: 'Arquivo da aplicação (.escadapkg)', packageDescription: 'Arquivo único e portável com manifesto, Engineering canônico, imagens do projeto e verificação de integridade. Working e Revisions permanecem persistidos pelo servidor.',
    downloadPackage: 'Salvar aplicação como…', packageSource: 'Arquivo da aplicação para abrir', choosePackage: 'Escolher arquivo .escadapkg', inspectPackage: 'Inspecionar aplicação',
    previewPackage: 'Validar Preview do restore', restorePackage: 'Restaurar no Working', packageNotInspected: 'Selecione e inspecione um pacote antes de validar o restore.',
    manifest: 'Manifesto do pacote', packageId: 'ID do pacote', createdAt: 'Criado em', format: 'Formato', projectIdentity: 'Projeto do pacote',
    packageSchema: 'Schema do Engineering', packagePayload: 'Conteúdo do Engineering', items: 'entidades', checksum: 'SHA-256', bytes: 'bytes',
    previewTitle: 'Resultado do Preview', create: 'Criar', update: 'Atualizar', skip: 'Ignorar', errors: 'Erros', canApply: 'Pode aplicar', blocked: 'Bloqueado',
    noPreview: 'Não há Preview validado para esta origem e modo de merge.', issues: 'Problemas de validação', noIssues: 'Nenhum problema de validação informado.',
    secretsTitle: 'Limite do backup', secretsHint: 'Arquivos de projeto nunca incorporam material secreto. Referências de segredo podem ser preservadas, mas credenciais permanecem no provedor de segredos configurado.',
    excludedTitle: 'Não incluído no .escadapkg v1', excluded: ['Amostras de séries temporais do historiador', 'Valores transitórios do Runtime', 'Sessões ativas', 'Senhas, tokens, chaves privadas ou hashes de credenciais', 'Segredos de implantação e do sistema operacional'],
    applyConfirmTitle: 'Aplicar o JSON canônico no Working?', applyConfirmDescription: 'Somente a origem e o modo exatos validados pelo Preview serão aplicados. Se o Working mudou nesse intervalo, o servidor rejeita a operação por conflito.', applyConfirm: 'Aplicar JSON validado',
    restoreConfirmTitle: 'Restaurar o backup no Working?', restoreConfirmDescription: 'Isso altera o Engineering Working atual usando o pacote e modo validados. Published e Active continuam sendo operações separadas do ciclo.', restoreConfirm: 'Restaurar backup validado',
    cancel: 'Cancelar', savedJson: 'JSON canônico do Engineering baixado.', savedPackage: 'Arquivo da aplicação salvo.',
    jsonApplied: 'JSON canônico aplicado ao Working.', packageRestored: 'Backup do projeto restaurado no Working.', packageInspected: 'Integridade e manifesto do pacote validados.',
    previewReady: 'Preview validado. O Apply permanece vinculado à origem, modo e versão exatos do Workspace.',
    authorityTitle: 'Autoridade do servidor preservada', authorityHint: 'Validação, merge, autorização EngineeringModify, Audit e proteção de concorrência permanecem no servidor. Este workspace não cria modelo privado do projeto nem identidade confiável do operador.'
  };
}
