<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Scada.Drivers/Scada.Drivers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dnp3" Version="1.6.0" />
  </ItemGroup>
</Project>
