listener 8883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/tls/passwords
cafile /mosquitto/config/tls/ca.crt
certfile /mosquitto/config/tls/server.crt
keyfile /mosquitto/config/tls/server.key
tls_version tlsv1.2
require_certificate false
persistence false
connection_messages true
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
