import React, { useEffect, useMemo, useState } from 'react';
import { clientMemory } from '../../runtime/clientMemory';
import type { EngineeringLocale } from '../i18n';
import { loadEngineeringSnapshot } from '../api';
import { buildScriptAssistantCatalog, type ScriptAssistantCatalog } from './scriptAssistantModel';
import {
  validateScriptAssistantReferences,
  type ScriptAssistantReferenceDiagnostic
} from './scriptAssistantReferenceValidation';
import './script-assistant.css';

type Props = Readonly<{
  locale: EngineeringLocale;
  source: string;
}>;

const copy = {
  'pt-BR': {
    title: 'Validação de referências do projeto',
    hint: 'Validação conservadora das referências literais geradas pelo assistente. Referências dinâmicas não são adivinhadas nem corrigidas automaticamente.',
    tag: 'TAG removida ou indisponível',
    object: 'Objeto removido ou indisponível',
    property: 'Propriedade não existe mais no schema canônico do objeto',
    memory: 'Client Memory removida ou indisponível',
    line: 'linha'
  },
  en: {
    title: 'Project reference validation',
    hint: 'Conservative validation of literal references generated by the assistant. Dynamic references are not guessed or auto-corrected.',
    tag: 'TAG was removed or is unavailable',
    object: 'Object was removed or is unavailable',
    property: 'Property no longer exists in the object canonical schema',
    memory: 'Client Memory was removed or is unavailable',
    line: 'line'
  },
  es: {
    title: 'Validación de referencias del proyecto',
    hint: 'Validación conservadora de referencias literales generadas por el asistente. Las referencias dinámicas no se adivinan ni se corrigen automáticamente.',
    tag: 'TAG eliminada o no disponible',
    object: 'Objeto eliminado o no disponible',
    property: 'La propiedad ya no existe en el schema canónico del objeto',
    memory: 'Client Memory eliminada o no disponible',
    line: 'línea'
  }
} as const satisfies Record<EngineeringLocale, Record<string, string>>;

export function PythonScriptReferenceDiagnostics({ locale, source }: Props) {
  const text = copy[locale] ?? copy.en;
  const [catalog, setCatalog] = useState<ScriptAssistantCatalog | null>(null);

  useEffect(() => {
    let active = true;
    void Promise.all([loadEngineeringSnapshot(), clientMemory.ensureInitialized()])
      .then(([snapshot]) => {
        if (!active) return;
        setCatalog(buildScriptAssistantCatalog(snapshot.package, clientMemory.snapshotSources()));
      })
      .catch(() => {
        if (active) setCatalog(null);
      });
    return () => { active = false; };
  }, []);

  const diagnostics = useMemo(
    () => catalog ? validateScriptAssistantReferences(source, catalog) : [],
    [catalog, source]
  );

  if (diagnostics.length === 0) return null;

  return (
    <section className="script-assistant" data-testid="script-reference-diagnostics" aria-label={text.title}>
      <header className="script-assistant__header">
        <div>
          <strong>{text.title}</strong>
          <span>{text.hint}</span>
        </div>
      </header>
      <div className="script-assistant__cards">
        {diagnostics.map((diagnostic, index) => (
          <article className="script-assistant__card script-assistant__card--compact" key={`${diagnostic.code}:${diagnostic.line}:${diagnostic.column}:${index}`}>
            <strong>{diagnosticLabel(diagnostic, text)}</strong>
            <span>
              {text.line} {diagnostic.line}:{diagnostic.column} · <code>{diagnostic.reference}</code>
              {diagnostic.propertyKey ? <> · <code>{diagnostic.propertyKey}</code></> : null}
            </span>
          </article>
        ))}
      </div>
    </section>
  );
}

function diagnosticLabel(
  diagnostic: ScriptAssistantReferenceDiagnostic,
  text: typeof copy.en
): string {
  if (diagnostic.code === 'SCRIPT_REFERENCE_TAG_MISSING') return text.tag;
  if (diagnostic.code === 'SCRIPT_REFERENCE_OBJECT_MISSING') return text.object;
  if (diagnostic.code === 'SCRIPT_REFERENCE_PROPERTY_MISSING') return text.property;
  return text.memory;
}
