import type { EngineeringLocale } from '../i18n';

const copy = {
  'pt-BR': {
    title: 'Assistente de Script / Objetos do Projeto',
    subtitle: 'Descubra objetos reais do Working project e insira Python canônico no cursor.',
    search: 'Pesquisar TAG, tela, objeto, propriedade, Dynamo ou API',
    refresh: 'Atualizar projeto',
    loading: 'Carregando objetos canônicos do projeto…',
    loadError: 'Não foi possível carregar o Project Object Browser.',
    tags: 'TAGs',
    screens: 'Telas',
    popups: 'Popups',
    clientMemory: 'Client Memory',
    capabilities: 'APIs disponíveis',
    empty: 'Nenhum item corresponde à pesquisa.',
    read: 'Ler',
    write: 'Escrever',
    clear: 'Limpar override',
    tween: 'Tween',
    insert: 'Inserir',
    canonicalReference: 'Referência canônica',
    dataType: 'Tipo',
    source: 'Source',
    driver: 'Driver',
    writable: 'Gravável',
    readOnly: 'Somente leitura',
    properties: 'Propriedades',
    events: 'Eventos',
    click: 'Click',
    addAction: 'Adicionar ação',
    chooseAction: 'Escolha a família da ação e depois o objeto real.',
    actionTag: 'TAG',
    actionVisual: 'Propriedade visual',
    actionMemory: 'Client Memory',
    actionCustom: 'Python personalizado',
    publicInterface: 'Interface pública do Dynamo',
    noProperties: 'Nenhuma propriedade canônica foi publicada para este tipo.',
    schemaUnknown: 'Tipo sem schema visual canônico conhecido. Nenhuma propriedade foi inventada.',
    runtimeContextOnly: 'A API visual atual só permite o Runtime Visual Instance que disparou este script.',
    multipleVisualTargets: 'Este script está ligado a múltiplos objetos; uma referência visual fixa não é segura em todos os disparos.',
    noVisualTarget: 'Este script ainda não possui um objeto visual proprietário para autorizar esta ação.',
    authorizedAtRuntime: 'A escrita passa pela autorização Runtime/backend e pode ser negada em execução.',
    stableSource: 'Source estável',
    legacySource: 'Source legado sem identidade estável',
    unresolvedSource: 'Source estável não resolvido',
    noSource: 'Sem Source',
    yes: 'Sim',
    no: 'Não',
    apiHint: 'Este catálogo deriva do bridge Client Visual desta build. Backend Operation pode continuar indisponível quando o host não fornecer provider.',
    dynamoHint: 'Somente parâmetros públicos são exibidos. Elementos internos permanecem encapsulados.',
    customInserted: 'Comentário de ação Python inserido no cursor.'
  },
  en: {
    title: 'Script Assistant / Project Objects',
    subtitle: 'Discover real Working project objects and insert canonical Python at the cursor.',
    search: 'Search TAG, screen, object, property, Dynamo or API',
    refresh: 'Refresh project',
    loading: 'Loading canonical project objects…',
    loadError: 'Project Object Browser could not be loaded.',
    tags: 'TAGs',
    screens: 'Screens',
    popups: 'Popups',
    clientMemory: 'Client Memory',
    capabilities: 'Available APIs',
    empty: 'No item matches the search.',
    read: 'Read',
    write: 'Write',
    clear: 'Clear override',
    tween: 'Tween',
    insert: 'Insert',
    canonicalReference: 'Canonical reference',
    dataType: 'Type',
    source: 'Source',
    driver: 'Driver',
    writable: 'Writable',
    readOnly: 'Read-only',
    properties: 'Properties',
    events: 'Events',
    click: 'Click',
    addAction: 'Add action',
    chooseAction: 'Choose an action family and then the real project object.',
    actionTag: 'TAG',
    actionVisual: 'Visual property',
    actionMemory: 'Client Memory',
    actionCustom: 'Custom Python',
    publicInterface: 'Dynamo public interface',
    noProperties: 'No canonical properties were published for this type.',
    schemaUnknown: 'No known canonical visual schema exists for this type. No properties were invented.',
    runtimeContextOnly: 'The current visual API only authorizes the Runtime Visual Instance that triggered this script.',
    multipleVisualTargets: 'This script is attached to multiple objects; one fixed visual reference is not safe for every dispatch.',
    noVisualTarget: 'This script does not yet own a visual object that can authorize this action.',
    authorizedAtRuntime: 'The write passes through Runtime/backend authorization and may still be denied during execution.',
    stableSource: 'Stable Source',
    legacySource: 'Legacy Source without stable identity',
    unresolvedSource: 'Unresolved stable Source',
    noSource: 'No Source',
    yes: 'Yes',
    no: 'No',
    apiHint: 'This catalog derives from this build’s Client Visual bridge. Backend Operation can remain unavailable when the host supplies no provider.',
    dynamoHint: 'Only public parameters are shown. Internal elements remain encapsulated.',
    customInserted: 'Custom Python action comment inserted at the cursor.'
  },
  es: {
    title: 'Asistente de Script / Objetos del Proyecto',
    subtitle: 'Descubra objetos reales del proyecto Working e inserte Python canónico en el cursor.',
    search: 'Buscar TAG, pantalla, objeto, propiedad, Dynamo o API',
    refresh: 'Actualizar proyecto',
    loading: 'Cargando objetos canónicos del proyecto…',
    loadError: 'No fue posible cargar el Project Object Browser.',
    tags: 'TAGs',
    screens: 'Pantallas',
    popups: 'Popups',
    clientMemory: 'Client Memory',
    capabilities: 'APIs disponibles',
    empty: 'Ningún elemento coincide con la búsqueda.',
    read: 'Leer',
    write: 'Escribir',
    clear: 'Limpiar override',
    tween: 'Tween',
    insert: 'Insertar',
    canonicalReference: 'Referencia canónica',
    dataType: 'Tipo',
    source: 'Source',
    driver: 'Driver',
    writable: 'Escribible',
    readOnly: 'Solo lectura',
    properties: 'Propiedades',
    events: 'Eventos',
    click: 'Click',
    addAction: 'Agregar acción',
    chooseAction: 'Elija una familia de acción y luego el objeto real del proyecto.',
    actionTag: 'TAG',
    actionVisual: 'Propiedad visual',
    actionMemory: 'Client Memory',
    actionCustom: 'Python personalizado',
    publicInterface: 'Interfaz pública del Dynamo',
    noProperties: 'No se publicaron propiedades canónicas para este tipo.',
    schemaUnknown: 'No existe un schema visual canónico conocido para este tipo. No se inventaron propiedades.',
    runtimeContextOnly: 'La API visual actual solo autoriza la Runtime Visual Instance que disparó este script.',
    multipleVisualTargets: 'Este script está asociado a múltiples objetos; una referencia visual fija no es segura para todos los disparos.',
    noVisualTarget: 'Este script todavía no posee un objeto visual que pueda autorizar esta acción.',
    authorizedAtRuntime: 'La escritura pasa por la autorización Runtime/backend y todavía puede ser rechazada en ejecución.',
    stableSource: 'Source estable',
    legacySource: 'Source legado sin identidad estable',
    unresolvedSource: 'Source estable no resuelto',
    noSource: 'Sin Source',
    yes: 'Sí',
    no: 'No',
    apiHint: 'Este catálogo deriva del bridge Client Visual de esta build. Backend Operation puede seguir indisponible cuando el host no provee provider.',
    dynamoHint: 'Solo se muestran parámetros públicos. Los elementos internos permanecen encapsulados.',
    customInserted: 'Comentario de acción Python insertado en el cursor.'
  }
} as const;

export type ScriptAssistantCopy = typeof copy['en'];

export function scriptAssistantCopy(locale: EngineeringLocale): ScriptAssistantCopy {
  return copy[locale] ?? copy.en;
}
