import type { EngineeringLocale } from '../i18n';

const copy = {
  'pt-BR': {
    title: 'Assistente de Script / Objetos do Projeto',
    subtitle: 'Descubra objetos reais da Área de trabalho e insira Python compatível no cursor.',
    search: 'Pesquisar TAG, tela, objeto, propriedade, Dynamo ou API',
    refresh: 'Atualizar projeto',
    loading: 'Carregando objetos do projeto…',
    loadError: 'Não foi possível carregar o Project Object Browser.',
    tags: 'TAGs',
    screens: 'Telas',
    popups: 'Popups',
    clientMemory: 'Client Memory',
    capabilities: 'APIs disponíveis',
    empty: 'Nenhum item corresponde à pesquisa.',
    read: 'Ler',
    write: 'Escrever',
    toggle: 'Alternar',
    show: 'Mostrar',
    hide: 'Ocultar',
    clear: 'Limpar override',
    tween: 'Tween',
    insert: 'Inserir',
    canonicalReference: 'Referência estável',
    visualDefinitionId: 'Visual Definition Id',
    visualObjectId: 'Stable Object Id',
    dataType: 'Tipo',
    source: 'Source',
    driver: 'Driver',
    equipment: 'Equipamento',
    dynamo: 'Dynamo',
    tag: 'TAG',
    runtimeRead: 'Leitura em Runtime',
    runtimeWrite: 'Escrita em Runtime',
    clearable: 'Clear permitido',
    binding: 'Binding',
    animation: 'Animação',
    current: 'Atual',
    value: 'Valor',
    unit: 'Unidade',
    enum: 'Enum',
    writable: 'Gravável',
    readOnly: 'Somente leitura',
    properties: 'Propriedades',
    events: 'Eventos',
    click: 'Click',
    addAction: 'Adicionar ação',
    chooseAction: 'Fluxo guiado: Evento → Ação → Objeto → Propriedade/Método → Parâmetros.',
    actionTag: 'TAG',
    actionVisual: 'Propriedade visual',
    actionMemory: 'Client Memory',
    actionCustom: 'Python personalizado',
    publicInterface: 'Interface pública do Dynamo',
    noProperties: 'Nenhuma propriedade disponível foi publicada para este tipo.',
    schemaUnknown: 'Tipo sem esquema visual conhecido. Nenhuma propriedade foi inventada.',
    runtimeContextOnly: 'A API visual atual só permite o Runtime Visual Instance que disparou este script.',
    multipleVisualTargets: 'Este script está ligado a múltiplos objetos; uma referência visual fixa não é segura em todos os disparos.',
    noVisualTarget: 'Este script ainda não possui um objeto visual proprietário para autorizar esta ação.',
    missingStableVisualIdentity: 'Este objeto não possui visualDefinitionId + visualObjectId estáveis; nova autoria visual está bloqueada.',
    eventObjectContext: 'Objeto/evento deste Script: os trechos usam IDs estáveis, não a Chave editável.',
    visualApiHelp: 'Exemplos Client Visual suportados',
    visualApiHelpHint: 'A autoria usa <visualDefinitionId>/<visualObjectId> + a chave estável da propriedade. objectKey é somente compatibilidade legada.',
    authorizedAtRuntime: 'A escrita passa pela autorização Runtime/backend e pode ser negada em execução.',
    stableSource: 'Source estável',
    legacySource: 'Source legado sem identidade estável',
    unresolvedSource: 'Source estável não resolvido',
    noSource: 'Sem Source',
    yes: 'Sim',
    no: 'Não',
    apiHint: 'Este catálogo deriva do bridge Client Visual desta build. Backend Operation pode continuar indisponível quando o host não fornecer provider.',
    dynamoHint: 'Somente parâmetros públicos são exibidos. Elementos internos permanecem encapsulados.',
    customInserted: 'Comentário de ação Python inserido no cursor.'
  },
  en: {
    title: 'Script Assistant / Project Objects',
    subtitle: 'Discover real Workspace objects and insert compatible Python at the cursor.',
    search: 'Search TAG, screen, object, property, Dynamo or API',
    refresh: 'Refresh project',
    loading: 'Loading project objects…',
    loadError: 'Project Object Browser could not be loaded.',
    tags: 'TAGs',
    screens: 'Screens',
    popups: 'Popups',
    clientMemory: 'Client Memory',
    capabilities: 'Available APIs',
    empty: 'No item matches the search.',
    read: 'Read',
    write: 'Write',
    toggle: 'Toggle',
    show: 'Show',
    hide: 'Hide',
    clear: 'Clear override',
    tween: 'Tween',
    insert: 'Insert',
    canonicalReference: 'Stable reference',
    visualDefinitionId: 'Visual Definition Id',
    visualObjectId: 'Stable Object Id',
    dataType: 'Type',
    source: 'Source',
    driver: 'Driver',
    equipment: 'Equipment',
    dynamo: 'Dynamo',
    tag: 'TAG',
    runtimeRead: 'Runtime read',
    runtimeWrite: 'Runtime write',
    clearable: 'Clear allowed',
    binding: 'Binding',
    animation: 'Animation',
    current: 'Current',
    value: 'Value',
    unit: 'Unit',
    enum: 'Enum',
    writable: 'Writable',
    readOnly: 'Read-only',
    properties: 'Properties',
    events: 'Events',
    click: 'Click',
    addAction: 'Add action',
    chooseAction: 'Guided flow: Event → Action → Object → Property/Method → Parameters.',
    actionTag: 'TAG',
    actionVisual: 'Visual property',
    actionMemory: 'Client Memory',
    actionCustom: 'Custom Python',
    publicInterface: 'Dynamo public interface',
    noProperties: 'No available properties were published for this type.',
    schemaUnknown: 'No known visual schema exists for this type. No properties were invented.',
    runtimeContextOnly: 'The current visual API only authorizes the Runtime Visual Instance that triggered this script.',
    multipleVisualTargets: 'This script is attached to multiple objects; one fixed visual reference is not safe for every dispatch.',
    noVisualTarget: 'This script does not yet own a visual object that can authorize this action.',
    missingStableVisualIdentity: 'This object has no stable visualDefinitionId + visualObjectId; new visual authoring is blocked.',
    eventObjectContext: 'Object/event context for this Script: snippets use stable IDs, not the editable Key.',
    visualApiHelp: 'Supported Client Visual examples',
    visualApiHelpHint: 'Authoring uses <visualDefinitionId>/<visualObjectId> + the stable property key. objectKey is legacy compatibility only.',
    authorizedAtRuntime: 'The write passes through Runtime/backend authorization and may still be denied during execution.',
    stableSource: 'Stable Source',
    legacySource: 'Legacy Source without stable identity',
    unresolvedSource: 'Unresolved stable Source',
    noSource: 'No Source',
    yes: 'Yes',
    no: 'No',
    apiHint: 'This catalog derives from this build’s Client Visual bridge. Backend Operation can remain unavailable when the host supplies no provider.',
    dynamoHint: 'Only public parameters are shown. Internal elements remain encapsulated.',
    customInserted: 'Custom Python action comment inserted at the cursor.'
  },
  es: {
    title: 'Asistente de Script / Objetos del Proyecto',
    subtitle: 'Descubra objetos reales del Área de trabajo e inserte Python compatible en el cursor.',
    search: 'Buscar TAG, pantalla, objeto, propiedad, Dynamo o API',
    refresh: 'Actualizar proyecto',
    loading: 'Cargando objetos del proyecto…',
    loadError: 'No fue posible cargar el Project Object Browser.',
    tags: 'TAGs',
    screens: 'Pantallas',
    popups: 'Popups',
    clientMemory: 'Client Memory',
    capabilities: 'APIs disponibles',
    empty: 'Ningún elemento coincide con la búsqueda.',
    read: 'Leer',
    write: 'Escribir',
    toggle: 'Alternar',
    show: 'Mostrar',
    hide: 'Ocultar',
    clear: 'Limpiar override',
    tween: 'Tween',
    insert: 'Insertar',
    canonicalReference: 'Referencia estable',
    visualDefinitionId: 'Visual Definition Id',
    visualObjectId: 'Stable Object Id',
    dataType: 'Tipo',
    source: 'Source',
    driver: 'Driver',
    equipment: 'Equipo',
    dynamo: 'Dynamo',
    tag: 'TAG',
    runtimeRead: 'Lectura en Runtime',
    runtimeWrite: 'Escritura en Runtime',
    clearable: 'Clear permitido',
    binding: 'Binding',
    animation: 'Animación',
    current: 'Actual',
    value: 'Valor',
    unit: 'Unidad',
    enum: 'Enum',
    writable: 'Escribible',
    readOnly: 'Solo lectura',
    properties: 'Propiedades',
    events: 'Eventos',
    click: 'Click',
    addAction: 'Agregar acción',
    chooseAction: 'Flujo guiado: Evento → Acción → Objeto → Propiedad/Método → Parámetros.',
    actionTag: 'TAG',
    actionVisual: 'Propiedad visual',
    actionMemory: 'Client Memory',
    actionCustom: 'Python personalizado',
    publicInterface: 'Interfaz pública del Dynamo',
    noProperties: 'No se publicaron propiedades disponibles para este tipo.',
    schemaUnknown: 'No existe un esquema visual conocido para este tipo. No se inventaron propiedades.',
    runtimeContextOnly: 'La API visual actual solo autoriza la Runtime Visual Instance que disparó este script.',
    multipleVisualTargets: 'Este script está asociado a múltiples objetos; una referencia visual fija no es segura para todos los disparos.',
    noVisualTarget: 'Este script todavía no posee un objeto visual que pueda autorizar esta acción.',
    missingStableVisualIdentity: 'Este objeto no tiene visualDefinitionId + visualObjectId estables; la nueva autoría visual está bloqueada.',
    eventObjectContext: 'Contexto de objeto/evento de este Script: los fragmentos usan IDs estables, no la Clave editable.',
    visualApiHelp: 'Ejemplos Client Visual soportados',
    visualApiHelpHint: 'La autoría usa <visualDefinitionId>/<visualObjectId> + la clave estable de la propiedad. objectKey es solo compatibilidad heredada.',
    authorizedAtRuntime: 'La escritura pasa por la autorización Runtime/backend y todavía puede ser rechazada en ejecución.',
    stableSource: 'Source estable',
    legacySource: 'Source legado sin identidad estable',
    unresolvedSource: 'Source estable no resuelto',
    noSource: 'Sin Source',
    yes: 'Sí',
    no: 'No',
    apiHint: 'Este catálogo deriva del bridge Client Visual de esta build. Backend Operation puede seguir indisponible cuando el host no provee provider.',
    dynamoHint: 'Solo se muestran parámetros públicos. Los elementos internos permanecen encapsulados.',
    customInserted: 'Comentario de acción Python insertado en el cursor.'
  }
} as const satisfies Record<EngineeringLocale, Record<string, string>>;

export type ScriptAssistantCopy = Readonly<Record<keyof typeof copy.en, string>>;

export function scriptAssistantCopy(locale: EngineeringLocale): ScriptAssistantCopy {
  return copy[locale] ?? copy.en;
}
